### ISSUE TITLE
Does django-tenants work with Django 1.11?

### ISSUE THREAD

**Issue by suriya** [tomturner/django-tenants#128]
Does django-tenants work with Django 1.11? It looks like the release 1.2.1 does not: https://github.com/tomturner/django-tenants/blob/b94c0ebb877e1f68b779ce016e44f72443c424f5/setup.py#L52

Are there any blockers when it comes to using Django 1.11 and django-tenants? If not, could you please make a new release?

**Comment by lorinkoz** [comment]
Getting this error with Django 1.11:

`AttributeError: module 'django.db.backends.postgresql_psycopg2.base' has no attribute 'DatabaseError'`

**Comment by suriya** [comment]
Could you please paste the full stacktrace?

**Comment by lorinkoz** [comment]
Windows 10 64 bits, Bash on Ubuntu

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7e9464e620>
Traceback (most recent call last):
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/d/Proyectos/some_app/source/enterprise/models/__init__.py", line 1, in <module>
    from .tenants import Business, Domain
  File "/mnt/d/Proyectos/some_app/source/enterprise/models/tenants.py", line 12, in <module>
    from django_tenants.models import TenantMixin, DomainMixin
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django_tenants/models.py", line 8, in <module>
    from .postgresql_backend.base import _check_schema_name
  File "/mnt/d/Proyectos/some_app/venv/lib/python3.5/site-packages/django_tenants/postgresql_backend/base.py", line 156, in <module>
    DatabaseError = original_backend.DatabaseError
AttributeError: module 'django.db.backends.postgresql_psycopg2.base' has no attribute 'DatabaseError'
```

**Comment by tomturner** [comment]
I will be looking at this soon

**Comment by suriya** [comment]
This error seems to be present in version 1.2.1. https://github.com/tomturner/django-tenants/blob/V1.2.1/django_tenants/postgresql_backend/base.py#L156 It looks like there is a fix in the master branch for this issue https://github.com/tomturner/django-tenants/commit/42eee0e0249290745ec28d8f0934203d8055afda

**Comment by tomturner** [comment]
I did all the work to make 1.11 work however I haven't put it PYPI yet

**Comment by tomturner** [comment]
All done
